apiVersion: skaffold/v2beta9
kind: Config
build:
  local:
    push: false
  artifacts:
  - image: mergetrain-backend
    context: backend
  - image: mergetrain-bot
    context: bot
deploy:
  helm:
    releases:
    - name: backend
      skipBuildDependencies: true
      chartPath: backend/chart/
      artifactOverrides:
        image: mergetrain-backend
      setValueTemplates:
        mongodb.auth.rootPassword: abc123123
    - name: bot
      skipBuildDependencies: true
      chartPath: bot/chart/
      artifactOverrides:
        image: mergetrain-bot
portForward:
- resourceType: service
  resourceName: backend-chart
  port: 80
  # localPort: 9000

profiles:
- name: prod
  activation:
    - kubeContext: do-sfo2-ribs
  build:
    local:
      push: true
    artifacts:
    - image: mergetrain-backend
      context: backend